M48
; DRILL file KiCad 10.0.3 date 2026-06-11T20:12:16
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-06-11T20:12:16-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X118.61Y-141.395
X124.39Y-141.395
T2
X58.5Y-34.0
X59.0Y-144.5
X184.0Y-34.0
X184.5Y-145.0
M30
